import type { Source } from "./types";

/**
 * P0 data sources (25) monitored by the daily crawler.
 * See tools/crawler/sources.yaml for the machine-readable version used by
 * the scraper.
 */
export const SOURCES: Source[] = [
  // International
  {
    id: "unece-wp29",
    name_en: "UNECE WP.29 / GRVA",
    name_cn: "联合国欧经委 WP.29 / GRVA 自动驾驶工作组",
    url: "https://unece.org/transport/road-transport/working-party-automatedautonomous-and-connected-vehicles-introduction",
    jurisdiction: "international",
    language: "en",
    robots_ok: true,
    crawl_frequency: "weekly",
  },
  {
    id: "iso-tc22-sc33",
    name_en: "ISO TC22/SC33 — Vehicle dynamics & chassis components",
    name_cn: "ISO TC22/SC33 汽车动力学及底盘部件分委会",
    url: "https://www.iso.org/committee/46706.html",
    jurisdiction: "international",
    language: "en",
    robots_ok: true,
    crawl_frequency: "weekly",
  },
  {
    id: "iso-sae-21434",
    name_en: "ISO/SAE 21434 Road-vehicle cybersecurity (joint)",
    name_cn: "ISO/SAE 21434 道路车辆信息安全（联合标准）",
    url: "https://www.iso.org/standard/70918.html",
    jurisdiction: "international",
    language: "en",
    robots_ok: true,
    crawl_frequency: "weekly",
  },

  // China
  {
    id: "sac",
    name_en: "Standardization Administration of China (SAC)",
    name_cn: "国家标准化管理委员会 (SAC)",
    url: "https://www.sac.gov.cn/",
    jurisdiction: "china",
    language: "cn",
    crawl_frequency: "daily",
  },
  {
    id: "sac-tc114",
    name_en: "SAC/TC114 — National Technical Committee on Automobiles",
    name_cn: "全国汽车标准化技术委员会 (SAC/TC114) · CATARC 秘书处",
    url: "http://www.catarc.org.cn/",
    jurisdiction: "china",
    language: "cn",
    crawl_frequency: "daily",
  },
  {
    id: "sac-tc114-sc34",
    name_en: "SAC/TC114/SC34 — Intelligent & Connected Vehicles Sub-committee",
    name_cn: "全国汽车标准化技术委员会智能网联汽车分技术委员会 (SC34)",
    url: "http://www.catarc.org.cn/",
    jurisdiction: "china",
    language: "cn",
    notes: "China's primary SDO for intelligent & connected vehicle standards.",
    crawl_frequency: "daily",
  },
  {
    id: "miit",
    name_en: "MIIT — Dept. of Equipment Industry I",
    name_cn: "工业和信息化部装备工业一司",
    url: "https://www.miit.gov.cn/",
    jurisdiction: "china",
    language: "cn",
    crawl_frequency: "daily",
  },
  {
    id: "samr",
    name_en: "SAMR — State Administration for Market Regulation",
    name_cn: "国家市场监督管理总局",
    url: "https://www.samr.gov.cn/",
    jurisdiction: "china",
    language: "cn",
    crawl_frequency: "daily",
  },
  {
    id: "mot",
    name_en: "Ministry of Transport",
    name_cn: "交通运输部",
    url: "https://www.mot.gov.cn/",
    jurisdiction: "china",
    language: "cn",
    crawl_frequency: "daily",
  },
  {
    id: "catarc",
    name_en: "CATARC — China Automotive Technology & Research Center",
    name_cn: "中国汽车技术研究中心 (CATARC)",
    url: "https://www.catarc.com/",
    jurisdiction: "china",
    language: "cn",
    crawl_frequency: "daily",
  },
  {
    id: "caeri",
    name_en: "CAERI — China Automotive Engineering Research Institute",
    name_cn: "中国汽车工程研究院 (CAERI / 中国汽研)",
    url: "https://www.caeri.com.cn/",
    jurisdiction: "china",
    language: "cn",
    crawl_frequency: "weekly",
  },
  {
    id: "cmc",
    name_en: "CMC — China Merchants Testing Vehicle Technology Research Institute",
    name_cn: "招商局检测车辆技术研究院 (CMC / 招商车研)",
    url: "https://www.cmcresearch.com/",
    jurisdiction: "china",
    language: "cn",
    crawl_frequency: "weekly",
  },
  {
    id: "beijing-cape",
    name_en: "Beijing High-Level Automated Driving Demonstration Zone",
    name_cn: "北京市高级别自动驾驶示范区",
    url: "https://www.bjcapedz.cn/",
    jurisdiction: "china",
    language: "cn",
    crawl_frequency: "weekly",
  },
  {
    id: "shanghai-icv",
    name_en: "Shanghai ICV Demonstration Zones (Lingang · Jiading)",
    name_cn: "上海智能网联汽车示范区（临港 / 嘉定）",
    url: "https://www.lgxc.gov.cn/",
    jurisdiction: "china",
    language: "cn",
    crawl_frequency: "weekly",
  },
  {
    id: "shenzhen-icv",
    name_en: "Shenzhen Intelligent Connected Vehicle Management Regulation",
    name_cn: "深圳经济特区智能网联汽车管理条例",
    url: "http://www.szrd.gov.cn/",
    jurisdiction: "china",
    language: "cn",
    crawl_frequency: "weekly",
  },

  // US
  {
    id: "nhtsa",
    name_en: "NHTSA — National Highway Traffic Safety Administration",
    name_cn: "美国国家公路交通安全管理局 (NHTSA)",
    url: "https://www.nhtsa.gov/",
    jurisdiction: "us",
    language: "en",
    crawl_frequency: "daily",
  },
  {
    id: "ca-dmv",
    name_en: "California DMV — Autonomous Vehicles Program",
    name_cn: "加州车辆管理局自动驾驶项目",
    url: "https://www.dmv.ca.gov/portal/vehicle-industry-services/autonomous-vehicles/",
    jurisdiction: "us",
    language: "en",
    crawl_frequency: "weekly",
  },
  {
    id: "sae",
    name_en: "SAE International — Mobility Standards",
    name_cn: "SAE 国际汽车工程师学会标准",
    url: "https://www.sae.org/standards/",
    jurisdiction: "us",
    language: "en",
    notes: "Tracks J3016, J3018, J3131, J3164, J3206, J3237, J3247, etc.",
    crawl_frequency: "weekly",
  },
  {
    id: "ul",
    name_en: "UL Standards & Engagement — Autonomous Vehicles",
    name_cn: "UL 标准与合作 · 自动驾驶领域 (UL 4600)",
    url: "https://ulse.org/focus-areas/travel-safety/autonomous-vehicles/",
    jurisdiction: "us",
    language: "en",
    crawl_frequency: "weekly",
  },
  {
    id: "ieee-sa",
    name_en: "IEEE Standards Association",
    name_cn: "IEEE 标准协会 (2846 / 2848 / P3128)",
    url: "https://standards.ieee.org/",
    jurisdiction: "us",
    language: "en",
    crawl_frequency: "weekly",
  },

  // EU / UK
  {
    id: "ec-transport",
    name_en: "European Commission DG MOVE",
    name_cn: "欧盟委员会交通总司",
    url: "https://transport.ec.europa.eu/",
    jurisdiction: "eu",
    language: "en",
    crawl_frequency: "weekly",
  },
  {
    id: "euroncap",
    name_en: "Euro NCAP — Assisted & Automated Driving",
    name_cn: "欧洲新车安全评鉴协会 (Euro NCAP)",
    url: "https://www.euroncap.com/",
    jurisdiction: "eu",
    language: "en",
    crawl_frequency: "weekly",
  },
  {
    id: "uk-ccav",
    name_en: "UK Centre for Connected and Autonomous Vehicles (CCAV)",
    name_cn: "英国网联与自动驾驶车辆中心 (CCAV)",
    url: "https://www.gov.uk/government/organisations/centre-for-connected-and-autonomous-vehicles",
    jurisdiction: "uk",
    language: "en",
    crawl_frequency: "weekly",
  },

  // Japan
  {
    id: "meti",
    name_en: "Ministry of Economy, Trade and Industry",
    name_cn: "日本经济产业省 (METI)",
    url: "https://www.meti.go.jp/english/",
    jurisdiction: "japan",
    language: "mixed",
    crawl_frequency: "weekly",
  },
  {
    id: "mlit",
    name_en: "Ministry of Land, Infrastructure, Transport and Tourism",
    name_cn: "日本国土交通省 (MLIT)",
    url: "https://www.mlit.go.jp/en/",
    jurisdiction: "japan",
    language: "mixed",
    crawl_frequency: "weekly",
  },
];
